### PR TITLE
fix: non required options

### LINKED ISSUE #4: Averages seem off
I love the output. Really really nice work! I can't wait to see where this project goes. 

I am trying to make sense of the numbers, and I feel the averages are off. 

Take a lot of the screenshot below. This was run with --allow-hrtime.

Screen Shot 2020-06-17 at 7 25 44 AM

A few things to notice. 

1. The total time shows ~8 seconds. This does seem correct from the totally scientific method of counting "# Mississippi".  =)
2. The average time show 0.0496 ms. If you multiple this by 10,000 you should get something close to the 8 seconds. And you do. 
3. The individual runs are fairly stable, with 9984 taking 0.2065ms. If you multiple this by 9984 you should get something close to 8 seconds in milliseconds. Instead, you show something closer to 34 seconds. 

So I feel like the individual runs can't be trusted. This feels less of a formatting problem. If it was supposed to be `0.02065` the average time should have matched given than 99.8% of the runs took the same time.

Sorry, I don't have the code in GitHub to reproduce. But the output seems to be off pretty consistently. I figured I am either missing what the bars are representing or something else is wrong. 

Thanks!

### LINKED ISSUE #5: Update to 0.1.0 changes requirements of options
Screen Shot 2020-06-18 at 7 02 52 AM

Once upgrading from 0.0.3 to 0.1.0, the options object became required, even if it's just a {}. 

Should this be optional? Or should the docs be updated to show it always having at least an optional empty object passed in?

I can open a PR if I get some direction on what is expected.

### PR DESCRIPTION
**Pull request by littletof**
Fixes: #5
Fixes: #4

With fix on `nocolor` to be default false

### CODE REVIEW

File: pretty_benchmark_result.ts [hunk 1]
```diff
@@ -21,7 +21,7 @@ export type prettyBenchmarkResultOptions =
 const c: Colorer = new Colorer();
 
 export function prettyBenchmarkResult(
-  options: prettyBenchmarkResultOptions,
+  options?: prettyBenchmarkResultOptions,
```
Comment (khrome83) [inline pretty_benchmark_result.ts:24]: you could do 

`options: prettyBenchmarkResultOptions = {}`


if you want to set defaults, in the body of the method - 
```ts
const defaultOptions = {
  nocolor: false,
};

// Then inside prettyBenchmarkResult
const opts = {...defaultOptions, ...options};
```

Then any user option would overload default.

File: pretty_benchmark_result.ts [hunk 2]
```diff
@@ -32,20 +32,20 @@ export function prettyBenchmarkResult(
 
 function _prettyBenchmarkResultCb(
   results: BenchmarkRunResult,
-  options: prettyBenchmarkResultOptions,
+  options?: prettyBenchmarkResultOptions,
 ) {
-  if (options.nocolor) c.setColorEnabled(false);
+  if (options && options.nocolor) c.setColorEnabled(false);
```
Comment (khrome83) [inline pretty_benchmark_result.ts]: With the pattern above, options will always be an object, so you can just check options.nocolor.

If you use the overload, then this would be `opts.nocolor`.

You can also do the new operator which TS supports and with none of the changes above, would become. 

`if (options?.nocolor) c.setColorEnabled(false);`

File: pretty_benchmark_result.ts (hunk 1 above)
Comment (littletof) [reply pretty_benchmark_result.ts:24]: I like the `?` better, but I know, that the current solution eg: https://github.com/littletof/prettyBenching/blob/bdaedc125ad5f002d7ad2ae3af72ba48c037e157/benchmark_result_card.ts#L49-L61 is very ugly. I may do a refactor, where I use the spreading instead.

File: pretty_benchmark_result.ts (hunk 2 above)
Comment (littletof) [reply pretty_benchmark_result.ts]: Thanks, dont know why I didnt use the `?`

File: pretty_benchmark_result.ts (hunk 1 above)
Comment (khrome83) [reply pretty_benchmark_result.ts:24]: yeah, I am supportive =)

File: pretty_benchmark_result.ts (hunk 2 above)
Comment (khrome83) [reply pretty_benchmark_result.ts]: =)

**Review by khrome83 — APPROVED** [review]

File: pretty_benchmark_result.ts (hunk 1 above)
Comment (littletof) [reply pretty_benchmark_result.ts:24]: Noted :)
